### ISSUE TITLE
Corner (routing)

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#426] opened 2019-07-19 11:50 UTC
When I did the first simulations (floor field, Tordeux, waiting areas) for KapaKrit the routing around corners does not work well. The agents do not use the whole space of the corners, so there is a huge congestion in front of the corners. I did several test with different parameters and routers, but the result is the same.
**Geometry:** [L-oT.xml.txt](https://github.com/JuPedSim/jpscore/files/3410942/L-oT.xml.txt)
**Tordeux:** [ini_L-oT-Tordeux.xml.txt](https://github.com/JuPedSim/jpscore/files/3410940/ini_L-oT-Tordeux.xml.txt)
![Tordeux](https://user-images.githubusercontent.com/38530070/61531151-50a54b80-aa26-11e9-8039-b746047cfec3.png)

With the model "gradnav" it works better, but there the agents are overlapping and I can not use it for KapaKrit anyway, because I need the "waiting areas".

**Gradnav:** [ini_L-oT-gradnav.xml.txt](https://github.com/JuPedSim/jpscore/files/3410941/ini_L-oT-gradnav.xml.txt)
![Gradnav](https://user-images.githubusercontent.com/38530070/61531152-51d67880-aa26-11e9-9c59-0b3dd3c13e9f.png)

Do I miss something in the model "Tordeux2015" to have better results at corners? If not, the routing around corners should really be adapted. For KapaKrit corners are critical bottlenecks. It would not make any sense to do further simulations without a more realistic routing (like in "gradnav").

**Comment by chraibi** [comment] 2019-07-19 15:58
The problem is not related to `Tordeux2015`, but ff-router-specific.

**Comment by anna-braun** [comment] 2019-07-21 19:41
Okay, but why does it work with ff-router and gradnav, but not with ff-router and Tordeux2015?

**Comment by schroedtert** [comment] 2019-11-06 13:28
@xuqiancheng  could you please check this issue?

First, start by debugging the desired direction 
- if N=1
- if N=20
Both cases for model 3 and model 4. 

Thank you!

**Comment by xuqiancheng** [comment] 2019-11-06 16:19
[Test_result.zip](https://github.com/JuPedSim/jpscore/files/3815525/Test_result.zip)
The result of N=[1,20] and model=[3,4].

**Comment by anna-braun** [comment] 2019-12-02 13:27
I tested the influence of the values of force_ped _a_ and _D_.
For _D_ the agents have a larger spacing between each other, which makes the walking around the corner more realistic but for free walking on corridors the spacing is to high and therefore unrealistic..
a=2, D=0.1: ![a-2_D-0 10](https://user-images.githubusercontent.com/38530070/69962537-8860eb80-150e-11ea-8a0b-7eb76c7b6e3c.png)
a=2, D=0.2: ![a-2_D-0 20](https://user-images.githubusercontent.com/38530070/69962538-8860eb80-150e-11ea-9c40-3cc964cba8ed.png)
a=2, D=0.3: ![a-2_D-0 30](https://user-images.githubusercontent.com/38530070/69962539-8860eb80-150e-11ea-8093-1d50f8d97f49.png)

Changing _a_ looks a bit better, but it looks like the agents would walk more in lines when increasing _a_. So I am not sure if it is enough to change only this parameter to solve the problem.
a=2, D=0.15: ![a-2_D-0 15](https://user-images.githubusercontent.com/38530070/69962619-a890aa80-150e-11ea-92a3-7987cdf297dd.png)
a=3, D=0.15: ![a-3_D-0 15](https://user-images.githubusercontent.com/38530070/69962777-08875100-150f-11ea-9f4c-5bb898c1bbe1.png)
a=5, D=0.15: ![a-5_D-0 15](https://user-images.githubusercontent.com/38530070/69962782-0c1ad800-150f-11ea-9566-ac7e0a583da4.png)

**Comment by gnendev** [comment] 2020-08-24 07:59
The main reason for the congestion in front of the corner seems to be that the agents are moving to the left too early.
The problem is independent of the underlying operational model and the router.
![traj_LoT](https://user-images.githubusercontent.com/69429609/91018288-b1229700-e5ef-11ea-85f4-2f14871e5bd5.png)
![IFD_I_traj_LoT_a=2 00_D=0 10 txt_id_14](https://user-images.githubusercontent.com/69429609/91018374-cbf50b80-e5ef-11ea-925f-cc5ce3577e04.jpg)
(Tordeux2015 with a=2.00 and D=0.10, ff_global_shortest)

**Comment by gnendev** [comment] 2020-08-24 08:02
Ways to lessen the problem:

(1) Parameter tuning (model)
It is likely to find parameter sets that are appropriate to reproduce the situation in front of the corner.
However, these may not be the optimal choice for the rest of the simulation.

(2) Waiting areas without waiting time (routing)
Due to the intermediate goal, the agents have a weaker desire of moving to the left (in front of the corner).
Among the consequences are an increased average velocity in front of the corner,
a reduced density in front of the corner, and a reduced evacuation time.
![traj_LoT_waiting_area](https://user-images.githubusercontent.com/69429609/91018926-884ed180-e5f0-11ea-942b-04ce1acb0a74.png)
![IFD_I_traj_LoT_a=2 00_D=0 10_waiting_area txt_id_14](https://user-images.githubusercontent.com/69429609/91018941-8dac1c00-e5f0-11ea-8ec1-74006c11d8d8.jpg)
(Tordeux2015 with a=2.00 and D=0.10, ff_global_shortest,
waiting area not optimized regarding shape and position)

**Comment by gnendev** [comment] 2020-08-24 08:05
In summary, the use of (2) gives more freedom for the use of (1).

**Comment by Ozaq** [comment] 2022-05-04 09:41
Gradnav has been removed and routing is beeing reworked from scratch. Agent behaviour in corners has to be reevaluated. I will close this issue since this will require a deep look at it outside of the discussion here.

**Closed by Ozaq** 2022-05-04 09:41 UTC
Labels: KapaKrit
