### ISSUE TITLE
JPScore stores trajecotry files in a convoluted path of directories.

### ISSUE THREAD

**Issue by JonasRzez** [JuPedSim/jpscore#448] opened 2019-08-01 13:45 UTC
**JuPedSim - JPScore**

Current date   : Aug  1 2019 14:46:17
Version        : 0.8.4
Compiler       : clang++ (10.0.1)
Commit hash    : v0.8.4-145-g9e20eda0
Commit date    : Tue Jul 30 16:47:41 2019
Branch         : develop

When running a demo scenario jpscore produces a convoluted path of directories to store the trajectory file:
</Users/jonas/Documents/FZJülichPHD/jupedsim/jpscore/build/Users/jonas/Documents/FZJülichPHD/jupedsim/jpscore/build/../demos/scenario_7_floorfield/Kobes_traj.xml>

instead of 

/Users/jonas/Documents/FZJülichPHD/jupedsim/jpscore/build/../demos/scenario_7_floorfield/Kobes_traj.xml

**Comment by chraibi** [comment] 2019-08-01 14:07
Tobi @schroedtert  could you please have a look?

**Comment by schroedtert** [comment] 2019-08-01 14:38
@chraibi Can you send me your CMake output, most important which compiler did you use?

**Comment by chraibi** [comment] 2019-08-01 14:50
![Screenshot 2019-08-01 22 48 36](https://user-images.githubusercontent.com/5772973/62303435-b1b13280-b4ae-11e9-84a3-6cddfdef9dca.png)

**Comment by chraibi** [comment] 2019-08-01 23:52
What is the outcome of this simulation, when you compile with `brew g++` or `port g++`?

Is this perhaps related to `boost::fs`?

**Comment by schroedtert** [comment] 2019-08-02 06:44
It is related to `boost::fs`, when I tried it with `std::fs` it worked fine.
Somehow `rel_path` is set to the absolute path, hence creating this convoluted path.

**Comment by chraibi** [comment] 2019-08-02 07:57
Oh! that's nasty! So `boost:fs` and `std::boost` have different behaviors. 

Maybe it's easy to fix though..

**Comment by Ozaq** [comment] 2019-08-02 08:06
@chraibi Just for clarification: The trajectories file shall be written to a path/name relative to the path where the ini file is located?

I think this could fix it:
```cpp
fs::path trajLoc( xTrajectories->FirstChildElement("file")->Attribute("location"));
fs::path root(_config->GetProjectRootDir()); // returns an absolute path already
fs::path canonicalPath = fs::weakly_cannonical(root / trajLoc);
std::string traj = cannonicalPath.string();
```

**Comment by schroedtert** [comment] 2019-08-02 08:29
Thanks, this fixes indeed the reading and creating of the filename. But still while writing the files there is something wrong. 
Small question what is the state of the art method for writing to files? 
At the moment we are using `basic_ofstream`

**Comment by Ozaq** [comment] 2019-08-02 08:35
> Thanks, this fixes indeed the reading and creating of the filename. But still while writing the files there is something wrong.

Yeah I see the same here... somethings amiss..

> Small question what is the state of the art method for writing to files?
> At the moment we are using `basic_ofstream`

ofstream is perfectly reasonable to use for what I have seen here so far.

**Comment by schroedtert** [comment] 2019-08-02 08:38
The problem is `std::fs` returns paths with a `/` at the end and `boost::fs` without ...

**Comment by Ozaq** [comment] 2019-08-02 08:40
> The problem is `std::fs` returns paths with a `/` at the end and `boost::fs` without ...

can you point to the code where this becomes a problem?

**Comment by schroedtert** [comment] 2019-08-02 08:46
Okay, maybe we have some duplicate code ... The same part as above is also in Simulation.cpp#156ff

**Comment by Ozaq** [comment] 2019-08-02 08:51
> Okay, maybe we have some duplicate code ... The same part as above is also in Simulation.cpp#156ff
This code seems to control the "default" output location in case it was not set in the ini file. Needs some refactoring...

> What operation on string is done with the `/=` operator?
None unless its implemented in jpscore anywhere... For all defaults see: https://en.cppreference.com/w/cpp/string/basic_string

**Comment by Ozaq** [comment] 2019-08-02 09:48
@JonasRzez @chraibi If you build from develop this should be fixed.

**Comment by chraibi** [comment] 2019-08-04 14:48
Thanks, guys! @Ozaq, @schroedtert 
 This works well for this example.

But not general enough, I fear. 


![Screenshot 2019-08-04 22 44 33](https://user-images.githubusercontent.com/5772973/62425083-a6a60e80-b709-11e9-85b0-657e77a1871a.png)

Running  with this version 
```
JuPedSim - JPScore

Current date   : Aug  4 2019 21:19:32
Version        : 0.8.4
Compiler       : clang++ (10.0.1)
Commit hash    : v0.8.4-153-g21b3867a
Commit date    : Fri Aug 2 17:44:17 2019
Branch         : develop
----
```

produces a SegFault plus a funny looking directory:

![Screenshot 2019-08-04 22 45 13](https://user-images.githubusercontent.com/5772973/62425108-d523e980-b709-11e9-854b-bc399f8d81eb.png)

**Comment by schroedtert** [comment] 2019-08-04 15:56
@chraibi quick fix for yourself: delete the new line in the traj file location and remove all `./` in front of the paths. But there seem to be some other issues, I’m checking on them.
Shouldn’t be there a `<header>` at the beginning of the ini-file?

**Comment by chraibi** [comment] 2019-08-04 16:03
@schroedtert 
- SegFault is gone. Header-section was missing. Maybe, in the future we could catch this missing header and exit with grace? 

- removing `./` works gut and the weird directory disappears.

**Comment by schroedtert** [comment] 2019-08-04 16:19
So header is required now? Maybe we should open a new issues relating to ini file and the format we want to have, etc. So that we can discuss and update the reading properly.
For the next steps: Should a leading whitespaces and `./` be considered or can we close this issue?

**Comment by chraibi** [comment] 2019-08-05 01:31
Yes, I would suggest "Header" debate in another issue.

I think `./` or even giving full path should be considered. There must be a function that detects this..

**Comment by Ozaq** [comment] 2019-08-08 09:41
> I think `./` or even giving full path should be considered. There must be a function that detects this..

I don't think having a fully qualified path is desirable because this varies from machine to machine, even user to user making the ini files machine/user specific and impossible to share. 

In any case paths can be tested with `is_absolute()` and `is_relative()` so this should be fixable. 

@chraibi Is there any doc available listing all the mandatory and optional input / output files?

**Comment by chraibi** [comment] 2019-08-13 04:24
@Ozaq I always find it not optimal when user-specific paths are written in the inifile. 
(not nice when sharing or reporting bugs)

What would you suggest in this case? Give an Error and an appropriate message forcing a certain use of paths?

Documentation:. That's all we've got so far http://www.jupedsim.org/jpscore/2016-11-01-inifile

**Comment by chraibi** [comment] 2019-08-13 05:26
@JonasRzez you ok now?

**Comment by JonasRzez** [comment] 2019-08-13 10:17
@chraibi  Yeah everything works fine now .

**Comment by Ozaq** [comment] 2019-08-13 22:02
> What would you suggest in this case? Give an Error and an appropriate message forcing a certain use of paths?

I am a big believer in "less is more" in cases as this, i.e. id rather be less flexible but easier to make robust. Reporting an error for absolute paths of output files sounds good to me, maybe even refuse any paths that are "escaping" the current working dir (i.e. "../"). Or being even more restrictive (simple to implement) and don't allow setting of any paths in the ini and allow `--output-path` as cmdline param that contains all output files. Last one being my favorite. 

References of input files in the generate output are a different can of worms though...

**Comment by chraibi** [comment] 2019-08-14 03:14
thanks @JonasRzez  for your feedback.

**Closed by chraibi** 2019-08-14 03:14 UTC
Labels: bug
