### ISSUE TITLE
Juelich Tests range in master xml file

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/jpscore#550] opened 2019-11-12 21:15 UTC
In the juelich test ini masterfiles the following expression exists:
```         <exit_crossing_strategy>range(1,5)</exit_crossing_strategy>```
Either it is wrong and should be `[1,2,3,4,5]` or it should be substituted correctly in the python script.

**Comment by chraibi** [comment] 2019-11-13 08:26
why is it wrong? Could it be because we don't have models from 1 to 5?

**Comment by zeroset** [comment] 2019-11-13 08:33
No, that's not the problem. I think the syntax is wrong and not used by the makeinifile.py script. It is simply not replaced.

**Comment by GuidoBasten** [comment] 2019-11-13 08:45
I think the makeinifile.py can't work with this Syntax. But it shoud be [1,2,3,4] if we chnage it.

**Comment by chraibi** [comment] 2019-11-13 09:00
This used to work with this syntax. :-(

**Comment by zeroset** [comment] 2019-11-13 10:48
I don't think it ever worked with this syntax. It just created, jupedsim interpreted this as 0 and took the default direction strategy.

**Comment by chraibi** [comment] 2019-11-13 11:10
The problem is that in Python3 `range()` is not `list`. Therefore, there is a small fix for this..

![bern](https://user-images.githubusercontent.com/5772973/68758613-6d394500-060e-11ea-8ac6-6cd4b6994fce.gif)

**Closed by chraibi** 2019-11-13 11:10 UTC
Labels: Priority: Medium, Status: Ready, Type: Bug
